import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link';

const navLinks = [
  {name: "Profile", href: "/profile"},
  {name: "Posts", href: "/posts"},
];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Friends App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {navLinks.map(link => {
            return <Link href={link.href} key={link.name}>{link.name}</Link>
        })}
        {children}
      </body>
    </html>
  );
}
